version: '3.9'

services:

  bot:
    restart: "always"
    build:
      dockerfile: Dockerfile
    command: sh -c "python telegram_bot.py"
    container_name: bot
    volumes:
      - ./sqlite.db:/TG_bot/sqlite.db
    env_file:
      - ./.env
    develop:
      watch:
        - path: libs/
          action: sync+restart